"""create Photo table

Revision ID: 82168954317d
Revises: 
Create Date: 2020-06-16 09:16:44.074955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82168954317d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_link'), 'photo', ['link'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photo_link'), table_name='photo')
    op.drop_table('photo')
    # ### end Alembic commands ###
