"""create CraftPhoto table

Revision ID: 94ab764313fa
Revises: 82168954317d
Create Date: 2020-06-16 09:41:39.988836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94ab764313fa'
down_revision = '82168954317d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('craft_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=200), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('photo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_craft_photo_link'), 'craft_photo', ['link'], unique=True)
    op.create_index(op.f('ix_craft_photo_timestamp'), 'craft_photo', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_craft_photo_timestamp'), table_name='craft_photo')
    op.drop_index(op.f('ix_craft_photo_link'), table_name='craft_photo')
    op.drop_table('craft_photo')
    # ### end Alembic commands ###
